name: Deploy to CapRover

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CapRover CLI
        run: npm install -g caprover

      - name: Deploy to CapRover
        run: |
          caprover deploy \
            --caproverUrl ${{ secrets.CAPROVER_SERVER }} \
            --appName ${{ secrets.CAPROVER_APPNAME }} \
            --appToken ${{ secrets.CAPROVER_PASSWORD }}
